import Footer from "@/components/common/footer/footer";
import localFont from "next/font/local";
import "../globals.css";
import type { Metadata } from "next";
import { Locale, i18n } from "@/config/i18n-config";
import { getSubdomainFromUrl } from "@/utils/get-subdomain-url";
import { cn } from "@/lib/utils";

// const HiraginoKakuGothic = localFont({
// 	src: "../../assets/fonts/hiragino-kaku-gothic-pro-w3.otf",
// 	variable: "--font-hiragino-kaku-gothic-pro",
// });

// Font files can be colocated inside of `pages`
const Helvetica = localFont({
	src: [
		{
			path: "../../assets/fonts/helvetica.woff",
			weight: "400",
		},
		{
			path: "../../assets/fonts/helvetica-bold.woff",
			weight: "600",
		},
	],
	variable: "--font-helvetica",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: string };
}) {
	const selectedLang = getSubdomainFromUrl(params.lang);
	return (
		<html lang={selectedLang}>
			<body
				className={cn(
					"min-h-screen antialiased font-helvetica",
					Helvetica.variable
				)}
			>
				{children}
				<Footer locale={selectedLang as Locale} />
			</body>
		</html>
	);
}
